spring:
  application:
    name: consumer
  rabbitmq:
    host: my-rabbit
    username: guest
    password: guest

spabbitecomm:
  rabbitmq:
    queue: order.query.queue

logging:
  file: spabbitecomm-query.log
  level:
    root: INFO
    org.springframework: INFO
    com.spabbit: DEBUG
    
info:
  app:
    name: spabbitecomm - query
    description: spabbitecomm - query
