version: "2"

services:

  my-mysql:
    container_name: my-mysql
    image: mysql/mysql-server:5.6
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_HOST=%

  my-rabbit:
    container_name: my-rabbit
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/etc/rabbitmq
#    volumes:
#      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
#      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODENAME: my-rabbit

  command:
    container_name: order-command
    image: spabbitecomm/order-command
    ports:
     - "8080:8080"
    depends_on:
     - my-rabbit
         
  query:
    container_name: order-query
    image: spabbitecomm/order-query
    depends_on:
     - my-rabbit
