version: "2"

services:

  my-rabbit:
    container_name: my-rabbit
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/etc/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODENAME: my-rabbit

  inventory-mongodb:
    image: mongo:2.4
    container_name: inventory-mongodb
    ports:
     - "27017:27017"
     - "28017:28017"

  inventory-command:
    container_name: inventory-command
    image: spabbitecomm/inventory-command
    ports:
     - "7000:7000"
    depends_on:
     - my-rabbit
     - inventory-mongodb

  inventory-elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    image: elasticsearch:2.4
    container_name: inventory-elasticsearch
    environment:
      - cluster.name=elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"

  inventory-query:
    container_name: inventory-query
    image: spabbitecomm/inventory-query
    ports:
     - "7001:7001"
    depends_on:
     - my-rabbit
     - inventory-elasticsearch

  order-mysql:
    container_name: order-mysql
    image: mysql/mysql-server:5.6
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_HOST=%

  order-command:
    container_name: order-command
    image: spabbitecomm/order-command
    ports:
     - "7050:7050"
    depends_on:
     - my-rabbit
     - order-mysql

  order-cron:
    container_name: order-cron
    image: spabbitecomm/order-cron
    depends_on:
     - my-rabbit
     - order-mysql
