server:
  port: ${PORT:7050}

spring:
  application:
    name: order-command
  rabbitmq:
    host: my-rabbit
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://order-mysql:3306/order
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    validation-query: SELECT 1

spabbitecomm:
  rabbitmq:
    orderExchange: order.exchange
    orderCreatedRoutingKey: order.created

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  file: spabbitecomm-command.log
  level:
    root: INFO
    org.springframework: INFO
    com.spabbitecomm: DEBUG
    
info:
  app:
    name: spabbitecomm - order command
    description: spabbitecomm - order command
