server:
  port: ${PORT:8080}

spring:
  application:
    name: producer
  rabbitmq:
    host: my-rabbit
    username: guest
    password: guest

spabbitecomm:
  rabbitmq:
    exchange: order.exchange
    queue: order.query.queue
    routingkey: order.created

logging:
  file: spabbitecomm-command.log
  level:
    root: INFO
    org.springframework: INFO
    com.spabbitecomm: DEBUG
    
info:
  app:
    name: spabbitecomm - producer
    description: spabbitecomm - producer
